/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely';

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type UserRole = 'manager' | 'reader';

export interface Collections {
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  description: string | null;
  id: Generated<string>;
  institution: string | null;
  name: string;
  updated_at: Generated<Timestamp>;
}

export interface Editions {
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  id: Generated<string>;
  notes: string | null;
  number: string | null;
  published_at: Timestamp | null;
  source_id: string;
  updated_at: Generated<Timestamp>;
}

export interface Sessions {
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: Generated<string>;
  user_id: string;
}

export interface Sources {
  collection_id: string;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  id: Generated<string>;
  language: string;
  metadata: Generated<Json>;
  name: string;
  type: string;
  updated_at: Generated<Timestamp>;
}

export interface Users {
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  email: string;
  id: Generated<string>;
  name: string;
  password_hash: string;
  role: Generated<UserRole>;
  updated_at: Generated<Timestamp>;
}

export interface DB {
  collections: Collections;
  editions: Editions;
  sessions: Sessions;
  sources: Sources;
  users: Users;
}
